name = "draft"
type = "webpack"
workers_dev = true
account_id = "3d1dc049912d9dd753352f2cee4b61c5"
zone_id = "f7f9f4d6025bf5e45372a1d9925ae4bb"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "5fcaabcf564e4771a45a9a37d34e77fb", id = "5fcaabcf564e4771a45a9a37d34e77fb" }
]

[env.staging]
name = "drive-staging"
